<a href="https://colab.research.google.com/github/harlee2/Linear-Algebra/blob/main/takehome_exam_2_harlee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [2]:
lll = " correctly!"

def rref(matrix):
    A = np.array(matrix, dtype=np.float64)
    
    r = 0 #row
    c = 0 #column

    (maxr, maxc) = A.shape

    prev_row_pivot = -1   # The previous row with a leading term:
    tmp_pivot_row = -1
    this_pivot_row = -1

    for c in range(maxc):  # go through each column
      tmp_pivot_row = -1  # reset the tmp pivot row
      this_pivot_row = -1  # reset this pivot row
      for r in range(maxr):  # Find the leading term in this column below prev_row_pivot
        if ((r > prev_row_pivot) and (A[r][c] != 0.0)):
          tmp_pivot_row = r  # find the new pivot row
      if (tmp_pivot_row > -1):  # we found a candidate for the leading term:
        #swap row this_pivot_row with (prev_row_pivot + 1)
        A[[tmp_pivot_row, prev_row_pivot+1]] = A[[prev_row_pivot + 1, tmp_pivot_row]]
        #set this_pivot_row to prev_row_pivot+1
        this_pivot_row = prev_row_pivot + 1
        #Now, normalize the row based on the pivot value:
        A[ this_pivot_row ] = A[ this_pivot_row ] / A[ this_pivot_row ][c]
        #Then, use this row to force 0's above and below the pivot entry:
        #subtract multiples of of the this_pivot_row row from the others
        for r_ in range(len(A)):
            if r_ != this_pivot_row:
                A[r_] = A[r_] - A[this_pivot_row] * A[r_][c] / A[this_pivot_row][c]
        prev_row_pivot = this_pivot_row
    return A   


def is_singular(matrix):
  singular = True
  notsingular = False

  (mr, mc) = matrix.shape
  
  return_value = notsingular
  if (mc - np.linalg.linalg.matrix_rank(matrix) > 0) :
    return_value = singular
  return return_value
 
    
    

print(">> The page ", ll, lll)

>> The page  loaded  correctly!


In [3]:
# create the matrix:
M = np.matrix([[1, -2, 4],
               [1, 0, 0],
               [1, -1, 1],
               [1, -1, 1]])


# create the vector for the right hand side:
pts = np.matrix([[-4], [-4], [5], [1]])
 
#Make sure the system looks appropriate:
print(np.c_[M,pts])

[[ 1 -2  4 -4]
 [ 1  0  0 -4]
 [ 1 -1  1  5]
 [ 1 -1  1  1]]


In [4]:
# Generate the transpose of M:
MT = M.transpose()

print("The Transpose of M is:")
print(MT)

# and find MT*M and MT*pts:
print("\n")
print("MT * M is: ")
MTM = MT * M
print(MTM)

print("\n")
print("MT * pts is:")
MTpts = MT * pts
print(MTpts)


The Transpose of M is:
[[ 1  1  1  1]
 [-2  0 -1 -1]
 [ 4  0  1  1]]


MT * M is: 
[[  4  -4   6]
 [ -4   6 -10]
 [  6 -10  18]]


MT * pts is:
[[ -2]
 [  2]
 [-10]]


In [5]:
#  Check if MTM is singular
is_singular(MT*M)

False

In [9]:
# If MTM is singular, then adjust one row of MTM and MT pts to be just 1's:

#MTM[2] is the entire 3rd row of MTM, 
#so MTM[2] = 1 will put 1's in MTM's 3rd row.

MTM[2] = 1
MTpts[2] = 1

print("MTM is now: ")
print(MTM)

print("and MTpts is now:")
print(MTpts)

print("Is our modified MTM singular?")
is_singular(MTM)

MTM is now: 
[[  4  -4   6]
 [ -4   6 -10]
 [  1   1   1]]
and MTpts is now:
[[-2]
 [ 2]
 [ 1]]
Is our modified MTM singular?


False

In [10]:
#Find our solution using the inverse of MTM:

#First, find the inverse of MTM:
MTMI = np.linalg.inv(MTM)

print("The inverse of MTM is:")
print(MTMI)

#Now, use the inverse of MTM to solve for the rankings:

print("\n")
print("The solution are rankings:")
MTMI * MTpts

The inverse of MTM is:
[[ 0.57142857  0.35714286  0.14285714]
 [-0.21428571 -0.07142857  0.57142857]
 [-0.35714286 -0.28571429  0.28571429]]


The solution are rankings:


matrix([[-0.28571429],
        [ 0.85714286],
        [ 0.42857143]])